name: bankSystem
main: bankplugin\Main
version: 1.
api:
 - 3.0.0
 - 3.0.1
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
load: POSTWORLD
author: masaiwasa
description: 銀行プラグイン
commands:
  bank:
    description: "銀行コマンド"
    usage: "/bank <dp|wp|info> <金額>"
