name: bankSystem
main: bankplugin\Main
version: 1.
api:
 - 3.0.0
load: POSTWORLD
author: masaiwasa
description: 銀行プラグイン
commands:
  bank:
    description: "銀行コマンド"
    usage: "/bank <dp|wp|info> <金額>"
